### ISSUE TITLE
Is there a license to use?

### ISSUE THREAD

**Issue by Eckart66** [xialinbo/DelaunayTriangulation#3]
Hi Xialinbo, 
I liked the idea of this algorithm, because it is very compact. 
We could probably use it with some modifications in one part of our project.

Could you add a license, so that others are allowed to use this algorithm idea and source,  code e.g. a MIT license?
Or did you use sources from other places?

Thanks and regards
Eckart

**Comment by xialinbo** [comment]
hi i added a MIT license file just now so feel free to use it.
I learnt the idea from a paper long time ago and the code is original.

**Comment by Eckart66** [comment]
Hi, 

thank you very much 
Nevertheless, I meanwhile had to switch to a different library. For big datasets there seem to be numerical instabilities where the algorithm flips to the wrong place...

Thanks and best regards
Eckart
