### ISSUE TITLE
Is it possible to increase the triangle mesh area ?

### ISSUE THREAD

**Issue by shalinsirwani** [xialinbo/DelaunayTriangulation#4]
Actually i liked the idea you used, Without using normals and many much complicated stuffs . 

Actually i have more than 57000 points , and i only want to consider those points which are far away from each other....

If you provide the answer immediately , it would be very useful to me.... please...

**Comment by xialinbo** [comment]
you can use clustering algorithm (K-means probably not good since K is large and not fixed, I would choose DBSCAN) first, and then pick any one dot from each cluster, that will be "those points which are far away from each other"
